[URLS]
tibiaPageUrl=https://penultimaotserv.online/
tibiaStoreGetCoinsUrl=https://penultimaotserv.online/donate
getPremiumUrl=https://penultimaotserv.online/donate
createAccountUrl=https://penultimaotserv.online/account/create
createTournamentCharacterUrl=https://penultimaotserv.online/account/create
accessAccountUrl=https://penultimaotserv.online/account/manage
lostAccountUrl=https://penultimaotserv.online/account/lost
manualUrl=https://penultimaotserv.online/serverinfo
faqUrl=https://penultimaotserv.online/faq
premiumFeaturesUrl=https://penultimaotserv.online/donate
limesurveyUrl=https://penultimaotserv.online/
hintsUrl=http://127.0.0.1/hints.json
cipSoftUrl=https://penultimaotserv.online/
twitchTibiaUrl=https://penultimaotserv.online/
youTubeTibiaUrl=https://penultimaotserv.online/
crashReportUrl=https://penultimaotserv.online/
fpsHistoryRecipient=https://penultimaotserv.online/
tutorialProgressWebService=https://penultimaotserv.online/
tournamentDetailsUrl=https://penultimaotserv.online/
;loginWebService=http://127.0.0.1:7171
;clientWebService=http://127.0.0.1:7171
;loginWebService=http://127.0.0.1:7171
;clientWebService=http://127.0.0.1:7171
;loginWebService=http://127.0.0.1:7171
;clientWebService=http://127.0.0.1:7171
loginWebService=http://127.0.0.1/login.php
clientWebService=http://127.0.0.1/login.php
             

[GRAPHICS]
; keep spritesheetCacheSize commented so that the automatic cache size mechanism becomes active
;spritesheetCacheSize=350
qsgAtlasWidth=4096
qsgAtlasHeight=4096
maximumNumberOfEffects=400
missileFlyDelayMsec=150
numericalEffectDisplayDurationMsec=1000
numericalEffectMergeDurationMsec=100
temporaryMarkDisplayDurationMsec=1000
renderLoopType=basic

[FPSHISTORY]
sampleRateMsec=30000
uploadRateSec=300

[NETWORK]
maxConcurrentDownloads=5

[MOVEMENT]
minPercentageOfCurrentMovementBeforeSendNext=1.0
maxMillisecondsToFinishCurrentMovementBeforeSendNext=0

[CHAT]
maxChatBacklogLength=100 
maxChatInputHistoryLength=100 
